# Generated by Django 6.0.7 on 2026-10-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='seats',
            new_name='seat',
        ),
    ]
